spring.datasource.url=jdbc:mysql://localhost:3306/systematpromo
spring.datasource.username=root
spring.datasource.password=Cl@23102006

jwt.secret=MPxeTm6HQ3IareE4coN0EGhNoa1kGC4w7af8OQqFjn+Ye0HJjbRyDfXdmU6j8657m5G0KD7kloVDWQXwpKS31A==
jwt.expiration-ms=86400000